#!/bin/sh

uci -q batch <<-EOF >/dev/null
    delete ucitrack.@radius[-1]
    add ucitrack radius
    set ucitrack.@radius[-1].exec="/usr/lib/radius.sh rebuild"
    commit ucitrack
EOF

cat <<-EOF >/etc/freeradius3/sites-enabled/default
authorize {
	eap {
		ok = return
	}
	files
}
authenticate {
	Auth-Type MS-CHAP {
		mschap
	}
	eap
}
accounting {
}
session {
}
EOF

/usr/lib/radius.sh rebuild

rm -f /tmp/luci-indexcache
exit 0
